package br.com.newcorretora.service.geraws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * 2017-12-12T11:56:32.302-02:00
 * Generated source version: 3.1.4.redhat-1
 * 
 */
@WebService(targetNamespace = "geraws", name = "SUDPOMSGPort")
@XmlSeeAlso({br.com.newcorretora.service.geraws.request.ObjectFactory.class, br.com.newcorretora.service.geraws.response.ObjectFactory.class})
public interface SUDPOMSGPort {

    @WebMethod
    @RequestWrapper(localName = "geraws", targetNamespace = "http://caixa.gov.br/geraws/request", className = "br.gov.caixa.geraws.request.ProgramInterface")
    @ResponseWrapper(localName = "gerawsResponse", targetNamespace = "http://caixa.gov.br/geraws/response", className = "br.gov.caixa.geraws.response.ProgramInterface")
    @WebResult(name = "web_sudwsmsg", targetNamespace = "http://caixa.gov.br/geraws/response")
    public br.com.newcorretora.service.geraws.response.ProgramInterface.WebSudwsmsg geraws(
        @WebParam(name = "web_sudwsmsg", targetNamespace = "http://caixa.gov.br/geraws/request")
        br.com.newcorretora.service.geraws.request.ProgramInterface.WebSudwsmsg webSudwsmsg
    );
}
